services:
  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=Password123!
      - MYSQL_DATABASE=minishop
    ports: ["3306:3306"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
